{% set name = "python-interface" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': 'b26a1c7fef45d32d473c9047b07618c66c66e2351f1ff6f71136bccf77f6c123'

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - interface
    - interface.tests
  requires:
    - pytest >=2.8.5
    - pytest-cov >=1.8.1
    - pytest-pep8 >=1.0.6
    - python {{ python_min }}

about:
  home: https://github.com/ssanderson/python-interface
  license: Apache-2.0
  license_family: APACHE
  # License file manually packaged. See https://github.com/ssanderson/python-interface/pull/40
  license_file: LICENSE
  summary: Pythonic Interface definitions

  description: |
    interface provides facilities for declaring interfaces and for statically asserting that classes implement those interfaces.
  doc_url: ''
  dev_url: https://github.com/ssanderson/python-interface

extra:
  recipe-maintainers:
    - gerrymanoim
    - jbredeche
    - jdricklefs
    - llllllllll
    - richafrank
